In [2]:
import numpy as np

an_array = np.array([12, 14, 2])

print(type(an_array))

<class 'numpy.ndarray'>


In [3]:
print(an_array.shape)

(3,)


In [4]:
print(an_array[0], an_array[1], an_array[2])

12 14 2


In [6]:
an_array[2] = 8
print(an_array)

[12 14  8]


In [10]:
# Rank 2 array
another = np.array([[26, 14, 2], [12, 3, 8]])
print("The row and the column nxm are: ", another.shape)
print(another[0][0], another[1][0])

The row and the column nxm are:  (2, 3)
26 12


In [13]:
# In build operations that can be performed using numpy
import numpy as np

zeros = np.zeros((2,2))
print(zeros)

[[0. 0.]
 [0. 0.]]


In [15]:
some_value = np.full((2,2), 26)
print(some_value)

[[26 26]
 [26 26]]


In [19]:
eye_matrix = np.eye(2, 2))
print(eye_matrix)

[[1. 0.]
 [0. 1.]]


In [22]:
one_matrix = np.ones((1,2))
print(one_matrix)

[[1. 1.]]


In [28]:
print(one_matrix.shape)
print()
print(one_matrix[0][1])

(1, 2)

1.0


In [33]:
# Create an random array float from 0 to 1
random_array = np.random.random((2,2))
print(random_array)

[[0.57822093 0.26566333]
 [0.49789414 0.97032617]]


In [39]:
print(np.random.random((3,1)).shape)

(3, 1)


## Slice Indexing

In [42]:
import numpy as np

# Preparing a 3x3 dimensional array
an_array = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(an_array)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [77]:
# Pull out the first two rows:
an_array_slice = an_array[:2, 1:3]
# To make a copy because by defaul the slices are by refrence
an_array_slice = np.array(an_array[:2, 1:3])

print("Before changing an_array: {} and an_array_slice: {}".format(an_array[0][1], an_array_slice[0][0]))
an_array_slice[0, 0] = 12 + 1 if an_array_slice[0][0] == 12 else 12
print("After changing an_array: {} and an_array_slice: {}".format(an_array[0][1], an_array_slice[0][0]))

print(an_array)
print(an_array_slice)

Before changing an_array: 12 and an_array_slice: 12
After changing an_array: 12 and an_array_slice: 13
[[11 12 13]
 [21 22 23]
 [31 32 33]]
[[13 13]
 [22 23]]


In [79]:

import numpy as np

# Preparing a 3x3 dimensional array
an_array = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(an_array)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [87]:
# Using both integer and slicing creates a lower ranked ndarry Rank-1
# a_slice = an_array[1, :]
a_slice = an_array[:, 1]
print(a_slice)
print(a_slice.shape)

[12 22 32]
(3,)


In [88]:
# Sliccing alone generates an array of the same rank.
# b_slice = an_array[1:2, :]
b_slice = an_array[:, 1:2]
print(b_slice)
print(b_slice.shape)

[[12]
 [22]
 [32]]
(3, 1)


## Array Indexing for changing elements

In [106]:
# Create a new array:
an_array = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33], [41, 42, 43]])
print("Original Array")
print(an_array[:2,])

Original Array
[[11 12 13]
 [21 22 23]]


In [94]:
col_indices = np.array([0, 1 , 2, 0])
print('\n Col indices picked: ', col_indices)


 Col indices picked:  [0 1 2 0]


In [97]:
row_indices = np.arange(4)
print('\n Row indices picked: ', row_indices)


 Row indices picked:  [0 1 2 3]


In [100]:
for (row, col) in zip(row_indices, col_indices):
    print(row ," ", col)

0   0
1   1
2   2
3   0


In [102]:
print("Value in the array in those indices are: ", an_array[row_indices, col_indices])

Value in the array in those indices are:  [11 22 33 41]


In [105]:
an_array[row_indices, col_indices] += 100000
print(an_array)

[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]
