In [2]:
import numpy as np

an_array = np.array([12, 14, 2])

print(type(an_array))

<class 'numpy.ndarray'>


In [3]:
print(an_array.shape)

(3,)


In [4]:
print(an_array[0], an_array[1], an_array[2])

12 14 2


In [6]:
an_array[2] = 8
print(an_array)

[12 14  8]


In [10]:
# Rank 2 array
another = np.array([[26, 14, 2], [12, 3, 8]])
print("The row and the column nxm are: ", another.shape)
print(another[0][0], another[1][0])

The row and the column nxm are:  (2, 3)
26 12


In [13]:
# In build operations that can be performed using numpy
import numpy as np

zeros = np.zeros((2,2))
print(zeros)

[[0. 0.]
 [0. 0.]]


In [15]:
some_value = np.full((2,2), 26)
print(some_value)

[[26 26]
 [26 26]]


In [19]:
eye_matrix = np.eye(2, 2))
print(eye_matrix)

[[1. 0.]
 [0. 1.]]


In [22]:
one_matrix = np.ones((1,2))
print(one_matrix)

[[1. 1.]]


In [28]:
print(one_matrix.shape)
print()
print(one_matrix[0][1])

(1, 2)

1.0


In [33]:
# Create an random array float from 0 to 1
random_array = np.random.random((2,2))
print(random_array)

[[0.57822093 0.26566333]
 [0.49789414 0.97032617]]


In [39]:
print(np.random.random((3,1)).shape)

(3, 1)


## Slice Indexing

In [42]:
import numpy as np

# Preparing a 3x3 dimensional array
an_array = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(an_array)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [77]:
# Pull out the first two rows:
an_array_slice = an_array[:2, 1:3]
# To make a copy because by defaul the slices are by refrence
an_array_slice = np.array(an_array[:2, 1:3])

print("Before changing an_array: {} and an_array_slice: {}".format(an_array[0][1], an_array_slice[0][0]))
an_array_slice[0, 0] = 12 + 1 if an_array_slice[0][0] == 12 else 12
print("After changing an_array: {} and an_array_slice: {}".format(an_array[0][1], an_array_slice[0][0]))

print(an_array)
print(an_array_slice)

Before changing an_array: 12 and an_array_slice: 12
After changing an_array: 12 and an_array_slice: 13
[[11 12 13]
 [21 22 23]
 [31 32 33]]
[[13 13]
 [22 23]]


In [79]:

import numpy as np

# Preparing a 3x3 dimensional array
an_array = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(an_array)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [87]:
# Using both integer and slicing creates a lower ranked ndarry Rank-1
# a_slice = an_array[1, :]
a_slice = an_array[:, 1]
print(a_slice)
print(a_slice.shape)

[12 22 32]
(3,)


In [88]:
# Sliccing alone generates an array of the same rank.
# b_slice = an_array[1:2, :]
b_slice = an_array[:, 1:2]
print(b_slice)
print(b_slice.shape)

[[12]
 [22]
 [32]]
(3, 1)


## Array Indexing for changing elements

In [106]:
# Create a new array:
an_array = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33], [41, 42, 43]])
print("Original Array")
print(an_array[:2,])

Original Array
[[11 12 13]
 [21 22 23]]


In [94]:
col_indices = np.array([0, 1 , 2, 0])
print('\n Col indices picked: ', col_indices)


 Col indices picked:  [0 1 2 0]


In [97]:
row_indices = np.arange(4)
print('\n Row indices picked: ', row_indices)


 Row indices picked:  [0 1 2 3]


In [100]:
for (row, col) in zip(row_indices, col_indices):
    print(row ," ", col)

0   0
1   1
2   2
3   0


In [102]:
print("Value in the array in those indices are: ", an_array[row_indices, col_indices])

Value in the array in those indices are:  [11 22 33 41]


In [105]:
an_array[row_indices, col_indices] += 100000
print(an_array)

[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]


In [21]:
# Boolean conditionaly check
import numpy as np
an_array = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])

filter_array = (an_array > 15)
print(filter_array)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [7]:
print(an_array[filter_array])

[21 22 23 31 32 33]


In [9]:
an_array[an_array > 15]

array([21, 22, 23, 31, 32, 33])

In [12]:
an_array[(an_array > 20) & (an_array < 30)]

array([21, 22, 23])

In [14]:
an_array[(an_array % 2) == 0]

array([12, 22, 32])

In [22]:
an_array[(an_array %2 )==0] += 100
print(an_array)

[[ 11 112  13]
 [ 21 122  23]
 [ 31 132  33]]


In [24]:
# Numpy Data types
an_array = np.array([26, 14]) # Python assigns the data type
print(an_array.dtype)

int64


In [25]:
an_array = np.array([26.0, 14.0]) # Python assigns the data type
print(an_array.dtype)

float64


In [26]:
an_array = np.array([26, 14], dtype=np.int64) # We explicitly assign the dtype for the array
print(an_array.dtype)

int64


In [27]:
# You can force the floats to be int numpy basically drop the decimal values and performs a literal floor
an_array = np.array([26.12, 14.03], dtype=np.int64)
print(an_array)

[26 14]


In [29]:
an_array = np.array([26, 14], dtype=np.float64)
print(an_array)

[26. 14.]


In [33]:
x = np.array([[111, 112], [121, 122]], dtype=np.int)
y = np.array([[211.1, 212.1], [221.1, 222.1]], dtype=np.float64)
print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [34]:
# Add arrays
print(np.add(x, y))
print()
print(x + y)

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [35]:
# subtract arrays
print(np.subtract(x, y))
print()
print(x - y)

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [36]:
# Multiply arrays
print(np.multiply(x, y))
print()
print(x * y)

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [38]:
# divide arrays
print(np.divide(x, y))
print()
print(x / y)

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [40]:
# Square root to all the elements
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [41]:
# Exp
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


<h1>Common ndArray function for data analysis including statistical, sorting and set Operations</h1>

In [45]:
import numpy as np

arr = 10 * np.random.randn(2, 5)
print(arr)

[[  8.15055472   7.7587995    0.64402244   8.67414847 -18.00898089]
 [ 10.08852151   2.62994785 -17.22955157   1.45881501 -18.27305894]]


In [47]:
# To compute the mean of the whole array
print(arr.mean())

-1.4106781913755033


In [48]:
# To compute the mean of the x-axis or rows
print(arr.mean(axis=1))

[ 1.44370885 -4.26506523]


In [49]:
# To compute the mean of the y-axis or columns
print(arr.mean(axis=0))

[  9.11953812   5.19437367  -8.29276457   5.06648174 -18.14101992]


In [51]:
print(arr.sum())

-14.106781913755032


In [53]:
# Compute the medians of each row
print(np.median(arr, axis=1))

[7.7587995  1.45881501]


# Sorting

In [56]:
# create an unsorted array
unsorted = np.random.randn(10) * 10
print(unsorted)

[  0.22273602  -8.72287984   4.48419294  15.83270964   4.40447281
  12.82913967  -3.11041281 -10.01629525   1.96007641   3.33018592]


In [57]:
# Create a copy and sort
sorted_ = np.array(unsorted)
sorted_.sort()
print(sorted_)

[-10.01629525  -8.72287984  -3.11041281   0.22273602   1.96007641
   3.33018592   4.40447281   4.48419294  12.82913967  15.83270964]


In [59]:
arr = np.array([1, 2, 1, 4, 2, 2, 1, 4 ])
print(np.unique(arr))

[1 2 4]


# Set operations with np.array data type

In [60]:
s1 = np.array(['chair', 'bulb', 'desk'])
s2 = np.array(['lamp', 'bulb', 'chair'])
print(s1, s2)

['chair' 'bulb' 'desk'] ['lamp' 'bulb' 'chair']


In [61]:
print(np.intersect1d(s1, s2))

['bulb' 'chair']


In [62]:
print(np.union1d(s1, s2))

['bulb' 'chair' 'desk' 'lamp']


In [64]:
print(np.setdiff1d(s2, s1))

['lamp']


In [65]:
print(np.in1d(s1, s2))

[ True  True False]


# Broadcasting

In [2]:
import numpy as np
start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
add_row = np.array([1, 0, 2])
print(add_row)

[1 0 2]


In [4]:
y = start + add_row
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [6]:
# Lets do it for row
# Create an array
add_cols = np.array([[0, 1, 2, 3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [7]:
y = start + add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [8]:
# Broadcasting using a scalar values
y = 1 + start
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Numpy Speed Test

In [40]:
from numpy import arange
from timeit import Timer

size = 1000000
timeits = 1000


In [41]:
nd_array = arange(size)
print(type(nd_array))

<class 'numpy.ndarray'>


In [42]:
timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")
print("Time taken is {}".format(timer_numpy.timeit(timeits)/timeits))

Time taken is 0.000701716296000086


In [43]:
nd_list = list(range(size))
print(type(nd_list))

<class 'list'>


In [45]:
timer_list = Timer("sum(nd_list)", "from __main__ import nd_list")
print("Time taken is {}".format(timer_list.timeit(timeits)/timeits))

Time taken is 0.007470165816999725
